### ISSUE TITLE
Appearence with Breeze Dark theme

### ISSUE THREAD

**Issue by Houston4444** [manucontrovento/SpinTool#1]
Hi.
You will see below how your software looks on KDE with Breeze Dark Theme.
I think I don't have to talk too much, the screenshot talks itself !

![superboucle](https://user-images.githubusercontent.com/3808689/78983556-bbeafc80-7b24-11ea-90a1-029160321386.png)

I didn't take time to test the software for the moment, I saw you renamed it, good point !

**Comment by manucontrovento** [comment]
wow! a bit messy :) 
I'll try to find the way to make the graphics not affected by theme.
Thanks!

**Comment by manucontrovento** [comment]
Hi @Houston4444  maybe I found the solution; I'll include it in next release, among other improvements

**Comment by Houston4444** [comment]
Are the modifications made on master branch ?
If it is the case, I can quickly test the master branch.

**Comment by manucontrovento** [comment]
Yes you could; but first you'll have to download the release of the "new" software (with the new name) or to download the whole master branch, which I updated after renaming the application, since following application name I changed all namespaces.

After dowloading current master branch or release, unpack in \spintool directory overwriting exhisting files:

[update_for_styles.zip](https://github.com/manucontrovento/SpinTool/files/4464232/update_for_styles.zip)

**Comment by manucontrovento** [comment]
Hi @Houston4444 

please try with new release:

https://github.com/manucontrovento/SpinTool/releases/tag/v20.04.13

and let me know

**Comment by Houston4444** [comment]
Hi.

Different but not really better !
PS: ./Spintool.sh needs a chmod +x

![Screenshot_20200413_180942](https://user-images.githubusercontent.com/3808689/79136912-10ef7280-7db2-11ea-8f73-ff70a7e6e0da.png)

**Comment by manucontrovento** [comment]
Hi! I don't know what to say, I thought that forcing stylesheets for all widgets (in previous version there were no stylesheets) would have forced the appearence to look as I see it.
It seems that the os theme affects the appearence overriding the stylesheets settings and at the moment I don't know how to change it.. I'll search on some forum.

Did you download new version and completely delete all files of the previous one?

**Comment by Houston4444** [comment]
This is with the new version (and there were no files remaining because of the name change).
Something else, console output says this multiple times (without doing anything).

Traceback (most recent call last):
  File "/home/houston/codes_sources/SpinTool-20.04.13/superboucle/gui.py", line 609, in onBeatOffsetChange
    self.last_clip.beat_offset = self.beat_offset.value()
AttributeError: 'NoneType' object has no attribute 'beat_offset'

Wait, this is python Qt, so I know well this, I'll take a look.

**Comment by manucontrovento** [comment]
Ok, interesting, I'll have a look at it.
It's strange because in my console I don't see that message. It's something I want to understand, however I don't think it's the reason of the strange appearence
Meanwhile I asked for some help in a forum, I'm quite sure that someone else has faced the same problem.

**Comment by sonejostudios** [comment]
@Houston4444  Just a question: Is this also happening with the original SuperBoucle from Vampouille?

**Comment by Houston4444** [comment]
Sorry, I made a mistake.
This message appears applying mouse wheel on the Beat amount spinBox .
In SuperBoucle, this groupBox  is not Enabled.

**Comment by sonejostudios** [comment]
@Houston4444 . Sorry to have been not precise enough...my question was, Is the whole dark theme problem also in original SuperBoucle from Vampouille?
(but good to know the beat amount spinbox problem is new! ;) )

**Comment by manucontrovento** [comment]
> 
> 
> Sorry, I made a mistake.
> This message appears applying mouse wheel on the Beat amount spinBox .
> In SuperBoucle, this groupBox is not Enabled.

Ok! Thanks! I will fix it!

**Comment by Houston4444** [comment]
@sonejostudios, no appearance problem in SuperBoucle.
Note I did test the last SuperBoucle release, not the master.

**Comment by manucontrovento** [comment]
It's true that it's my first time dealing with Qt, but I'm a bit confused about stylesheets... what's the use of defining them, if changing a theme it still affects the widgets?... 
there must be something obvious that I'm not catching

**Comment by sonejostudios** [comment]
This is interesting... if the problem was not in SB Master, what did you change @manucontrovento in the GUI so the proplem appears? Maybe just go back to the original theme? How did you change the gui, with QtDesigner or programmatically?

**Comment by manucontrovento** [comment]
I really can't reply to these questions.. because I don't know! I didn't intentionally change any theme.. I even didn't know that the application could have a theme. 
With Qt Designer I made my changes to the UI, and then when @Houston4444 reported me the problem, I assigned styilesheet to every UI element (window included) to be sure that they would appear as I decided.

**Comment by sonejostudios** [comment]
This is really weird because it should be the same on SB Master... @manucontrovento did you try to force the Qt Style?

**Comment by manucontrovento** [comment]
@sonejostudios if you mean the code you sent me, I'll try next days :)

**Comment by sonejostudios** [comment]
yes, this code! ;)

**Comment by manucontrovento** [comment]
Hi @Houston4444  
try downloading new spin.py module:

https://github.com/manucontrovento/SpinTool/blob/master/superboucle/spin.py

thanks to @sonejostudios  I found the way to force the theme. I realized I was wrong on how Qt manages its appearence. Maybe when SB was developed, system Qt theme was gtk2. So, its "real" appearence needs to be that theme.
Now on starting, gtk2 theme is applied.

**Comment by manucontrovento** [comment]
Hi @Houston4444 did you try the changes? It's included in latest release too.
If you don't see the problem anymore we can close the issue

**Comment by Houston4444** [comment]
Sorry no, it's exactly the same.
But as I run KDE Neon, I have always the last KDE version, and now I don't find anymore the GTK appearence configuration, I don't know what they have made, it can't be strange.

**Comment by manucontrovento** [comment]
Ok, now I understand! to properly work, Gtk theme is required. 
So first of all I should write it into prerequisites, since I don't see any other possible solution.
Or maybe I should find the way to download and install the theme along with other dependencies and requirements

**Comment by manucontrovento** [comment]
Hi, could we close the issue? did you try with gtk theme?

**Comment by manucontrovento** [comment]
Not getting any news I close the issue, if there will still be problems even with gtk theme present, we'll re-open the issue.
