### ISSUE TITLE
add menu item: save song as empty template or new songs preferred settings

### ISSUE THREAD

**Issue by sonejostudios** [manucontrovento/SpinTool#11]
saves an song with the ports and all the other settings but without any clips and samples

**Comment by manucontrovento** [comment]
We'll also consider another option: to change the "new song" dialog. There could be also a preferred master volume (suggesting 50), bpm, maybe beats number, and especially a field with a file selector to select a port list (main need is in fact to automatically have a port list when creating a new song).

We could save somewhere in settings the user' preferred starting settings. Maybe with specific options in Preferences, or maybe saving last used valures, or both (optionally). 

A third option could be to have a file picker in new song dialog to get the standard settings from an existing song (aka. create new song base on selected file).

**Comment by manucontrovento** [comment]
It will be in Next release
