### ISSUE TITLE
load playlist as cli argument

### ISSUE THREAD

**Issue by sonejostudios** [manucontrovento/SpinTool#16]
give a playlist as argument and load the first song of it.
(and don't save and loads the playlist from the settings?).
So, if you don't give arguments (or you give song) , the loaded playlist is last used (from Settings). But if you give a playlist as argument, it will be loaded and also first song in playlist will be loaded.

**Comment by manucontrovento** [comment]
> give a playlist as argument and load the first song of it.

it will be in next release!
