### ISSUE TITLE
Using with launchpad.py

### ISSUE THREAD

**Issue by vjustov** [manucontrovento/SpinTool#29]
Hello, Thank you for your work.

Im currently trying to run the app on a RaspberryPi 4 with a Launchpad MK1
this currently doesn't work because of reasons (to me) unknown. 
What would I need to do in order to connect the app with the [launchpad.py library](https://github.com/FMMT666/launchpad.py)?

**Comment by sonejostudios** [comment]
Hi! 
Until now SpinTool is only using standard midi configurations, which you can create in SpinTool. I'm using ST with a Launchpad S with Midi. If you like, I can send you my config file, or you create your own. Until now we didn't know about launchpad.py, which is a very interesting project! It would be nice to include into ST, but we both have right now no time to do it... I hope it will be possible soon!

**Comment by sonejostudios** [comment]
Actually, launchpad.py is using PyGame, and is not related to music. So I don't know why using it would be interesting for ST.

**Comment by vjustov** [comment]
ok, my current problem is that ST doesnt seem to recognize my Launchpad, id like to debug the issue is there a discord/gitter server where i can ask more beginner questions?

Where should i start to look to find what the problem is?

**Comment by sonejostudios** [comment]
Is your Launchpad recognized by jack? by alsa?
Is Launchpad MK1 using midi at all?

**Comment by vjustov** [comment]
Yes, it is recognized by ALSA (and im able to use it with other software like Giada)
![photo4936054580576364723](https://user-images.githubusercontent.com/4332586/96777980-4d4bfd00-13eb-11eb-9884-b9c8e8103fdb.jpg)

**Comment by sonejostudios** [comment]
ok. ST is using jack midi, which is different than alsa midi (look at the tab MIDI in jackctl, between Audio and ALSA).
You'll just need a Bridge, like a2jmidid. If it is installed, just type in the terminal:
`
a2jmidid -e`

Have a look to the MIDI tab, your launchpad should be visible. Then you'll need to connect in both directions.
![image](https://user-images.githubusercontent.com/12187481/96781758-65248080-13ed-11eb-8bd7-308330ec1419.png)

When you are there, you'll need to create a Midi Configuration in ST.
![image](https://user-images.githubusercontent.com/12187481/96783144-b9c7fb80-13ed-11eb-978e-724776299687.png)

**Comment by vjustov** [comment]
Oh, perfect that works! for the the controller, Thank you very much @sonejostudios 
(i would recommend adding that info to the wiki)

Now if i could just get the app to not crash (#30), been trying to debug it for the past 2 hr, 
but python is a new environment for me and i think its failing on some library side.

**Comment by sonejostudios** [comment]
you are welcome!

> (i would recommend adding that info to the wiki)

it is already ;)
Point 8. in https://github.com/manucontrovento/SpinTool/wiki/3.-Get-started
