### ISSUE TITLE
Font size in Playlist and Scene Managers

### ISSUE THREAD

**Issue by sonejostudios** [manucontrovento/SpinTool#7]
Hi @manucontrovento ,

this is a small feature I was thinking about for a long time. The possibility to change the font size of the Playlist and The Scene Managers. While on the stage, sometimes the computer has to be far away from the controller, and it is difficult to read. Maybe one could change this in the config dialog, or directly in the Manager's Dialog (like a "use big font" checkbox)
I think I could implement it, but I don't have time in the moment... maybe if you come across... or I'll do it in the future. However, I just wanted to write this thought somewhere, so is is done now ;)
Thank you for all the good work!
All the best,

Vince

**Comment by manucontrovento** [comment]
Hi, I was thinking about it as well :)
The solution could be font scaling. The other thing I was thinking about: a panel with big fonts which shows different kind of "messages" and tools. Do you remember Guitarix "live" mode? Something like that..

**Comment by sonejostudios** [comment]
I don't know Guitarix Live mode, but I'm sure it will also do the trick! ;)

**Comment by manucontrovento** [comment]
do you mean, like this?

![immagine](https://user-images.githubusercontent.com/56541575/80077595-02d9e880-854e-11ea-8456-2823314ac408.png)

done! 
you will have it in next release :)
